In [1]:
import pandas as pd
import torch
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import Normalization
from scipy import stats
from sklearn.preprocessing import normalize
from tensorflow.keras import layers
from tensorflow import keras
from keras import backend as K
import csv

Using TensorFlow backend.


In [2]:
test_data = pd.read_csv('test.csv')
train_data = pd.read_csv('train.csv')

test_data_scaled = test_data.copy()
train_data_scaled = train_data.copy()

print(test_data)
print(train_data)
test_data.dtypes
# test_data.values

        User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000004  P00128942      M  46-50           7             B   
1       1000009  P00113442      M  26-35          17             C   
2       1000010  P00288442      F  36-45           1             B   
3       1000010  P00145342      F  36-45           1             B   
4       1000011  P00053842      F  26-35           1             C   
...         ...        ...    ...    ...         ...           ...   
233594  1006036  P00118942      F  26-35          15             B   
233595  1006036  P00254642      F  26-35          15             B   
233596  1006036  P00031842      F  26-35          15             B   
233597  1006037  P00124742      F  46-50           1             C   
233598  1006039  P00316642      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               1                   1   
1            

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [3]:
##### Cek NaN data test #####

test_data[test_data.isnull().any(axis=1)]

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000004  P00128942      M  46-50           7             B   
1       1000009  P00113442      M  26-35          17             C   
2       1000010  P00288442      F  36-45           1             B   
3       1000010  P00145342      F  36-45           1             B   
9       1000022  P00067942      M  18-25          15             A   
...         ...        ...    ...    ...         ...           ...   
233593  1006036  P00255442      F  26-35          15             B   
233594  1006036  P00118942      F  26-35          15             B   
233595  1006036  P00254642      F  26-35          15             B   
233597  1006037  P00124742      F  46-50           1             C   
233598  1006039  P00316642      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               1                   1   
1                               0               0                   3   
2                              4+               1                   5   
3                              4+               1                   4   
9                              4+               0                   5   
...                           ...             ...                 ...   
233593                         4+               1                   8   
233594                         4+               1                   8   
233595                         4+               1                   5   
233597                         4+               0                  10   
233598                         4+               1                   4   

        Product_Category_2  Product_Category_3  
0                     11.0                 NaN  
1                      5.0                 NaN  
2                     14.0                 NaN  
3                      9.0                 NaN  
9                     14.0                 NaN  
...                    ...                 ...  
233593                 NaN                 NaN  
233594                 NaN                 NaN  
233595                 8.0                 NaN  
233597                16.0                 NaN  
233598                 5.0                 NaN  

[162562 rows x 11 columns]

In [23]:
a = test_data.count()
print(a)

User_ID                       233599
Product_ID                    233599
Gender                        233599
Age                           233599
Occupation                    233599
City_Category                 233599
Stay_In_Current_City_Years    233599
Marital_Status                233599
Product_Category_1            233599
Product_Category_2            233599
Product_Category_3            233599
dtype: int64


In [21]:
b = test_data['Product_Category_2'].value_counts()
print(b)
test_data = test_data.fillna({'Product_Category_2':8.0})

8.0     27229
14.0    23726
2.0     21281
16.0    18432
15.0    16259
4.0     11028
5.0     10930
6.0      7109
11.0     6096
17.0     5784
13.0     4523
9.0      2484
12.0     2273
10.0     1377
18.0     1257
3.0      1239
7.0       228
Name: Product_Category_2, dtype: int64


In [22]:
c = test_data['Product_Category_3'].value_counts()
print(c)
test_data = test_data.fillna({'Product_Category_3':16.0})

16.0    13833
15.0    11955
14.0     7855
5.0      7141
17.0     7116
8.0      5299
9.0      4953
12.0     3869
13.0     2390
6.0      1998
18.0     1992
4.0       816
11.0      780
10.0      775
3.0       265
Name: Product_Category_3, dtype: int64


In [24]:
##### encode the test data ######
print(test_data.dtypes)

eb = pd.get_dummies(test_data, columns=['Gender','Age','City_Category','Stay_In_Current_City_Years'])
print(eb)
print(eb.dtypes)

x_val_all = eb.copy()
x_val = x_val_all.drop(columns=['User_ID','Product_ID'])
print(x_val.shape)

x_val_np = x_val.to_numpy().astype('float64')
# x_val_norm = normalize(x_val_np)
# print(x_val_norm.shape)

x_val_scaled = scaler.fit_transform(x_val_np)
print(x_val_scaled.shape)

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object
        User_ID Product_ID  Occupation  Marital_Status  Product_Category_1  \
0       1000004  P00128942           7               1                   1   
1       1000009  P00113442          17               0                   3   
2       1000010  P00288442           1               1                   5   
3       1000010  P00145342           1               1                   4   
4       1000011  P00053842           1               0                   4   
...         ...        ...         ...             ...                 ...   
233594  1006036  P0011

In [8]:
##### Cek NaN data train #####

train_data[train_data.isnull().any(axis=1)]

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
5       1000003  P00193542      M  26-35          15             A   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
5                               3               0                   1   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
5                      2.0                 NaN     15227  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[383247 rows x 12 columns]

In [25]:
m = train_data.count()
print(m)

User_ID                       550068
Product_ID                    550068
Gender                        550068
Age                           550068
Occupation                    550068
City_Category                 550068
Stay_In_Current_City_Years    550068
Marital_Status                550068
Product_Category_1            550068
Product_Category_2            550068
Product_Category_3            550068
Purchase                      550068
dtype: int64


In [26]:
n = train_data['Product_ID'].value_counts()
print(n)
# test_data = test_data.fillna({'Gender':'Male'})

P00265242    1880
P00025442    1615
P00110742    1612
P00112142    1562
P00057642    1470
             ... 
P00234942       1
P00144942       1
P00298842       1
P00309642       1
P00172642       1
Name: Product_ID, Length: 3631, dtype: int64


In [27]:
o = train_data['Product_Category_2'].value_counts()
print(o)
train_data = train_data.fillna({'Product_Category_2':8.0})

8.0     237726
14.0     55108
2.0      49217
16.0     43255
15.0     37855
5.0      26235
4.0      25677
6.0      16466
11.0     14134
17.0     13320
13.0     10531
9.0       5693
12.0      5528
10.0      3043
3.0       2884
18.0      2770
7.0        626
Name: Product_Category_2, dtype: int64


In [28]:
p = train_data['Product_Category_3'].value_counts()
print(p)
train_data = train_data.fillna({'Product_Category_3':16.0})

16.0    415883
15.0     28013
14.0     18428
17.0     16702
5.0      16658
8.0      12562
9.0      11579
12.0      9246
13.0      5459
6.0       4890
18.0      4629
4.0       1875
11.0      1805
10.0      1726
3.0        613
Name: Product_Category_3, dtype: int64


In [29]:
##### encode the train data ######
print(train_data.dtypes)

fb = pd.get_dummies(train_data, columns=['Gender','Age','City_Category','Stay_In_Current_City_Years'])
print(fb)
print(fb.dtypes)

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object
        User_ID Product_ID  Occupation  Marital_Status  Product_Category_1  \
0       1000001  P00069042          10               0                   3   
1       1000001  P00248942          10               0                   1   
2       1000001  P00087842          10               0                  12   
3       1000001  P00085442          10               0                  12   
4       1000002  P00285442          16               0                   8   
...         ...        ...         ...             ...        

In [30]:
##### separate x and y, train and test

#### data fb

x_all = fb.copy()
# print(x_all)

x = x_all.drop(columns=['User_ID','Product_ID','Purchase'])
y = x_all['Purchase']
# print(x)
# print(y)

##### convert to numpy
x_np = x.to_numpy().astype('float64')
y_np = y.to_numpy().astype('float64')
print(x_np)
print(y_np)

y_np.resize((len(y_np),1))
print(y_np)

# x_np_norm = normalize(x_np)
# y_np_norm = normalize(y_np)
# print(x_np_norm)
# print(y_np_norm)

scaler = MinMaxScaler()

x_np_scaled = scaler.fit_transform(x_np)
y_np_scaled = scaler.fit_transform(y_np)

print(x_np_scaled)
print(y_np_scaled)

##### split into x_tr, x_te, y_tr, y_te
x_train, x_test, y_train, y_test = train_test_split(x_np_scaled,y_np_scaled,train_size=0.90)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)
print(y_test)

[[10.  0.  3. ...  1.  0.  0.]
 [10.  0.  1. ...  1.  0.  0.]
 [10.  0. 12. ...  1.  0.  0.]
 ...
 [15.  1. 20. ...  0.  0.  1.]
 [ 1.  0. 20. ...  1.  0.  0.]
 [ 0.  1. 20. ...  0.  0.  1.]]
[ 8370. 15200.  1422. ...   137.   365.   490.]
[[ 8370.]
 [15200.]
 [ 1422.]
 ...
 [  137.]
 [  365.]
 [  490.]]
[[0.5        0.         0.10526316 ... 1.         0.         0.        ]
 [0.5        0.         0.         ... 1.         0.         0.        ]
 [0.5        0.         0.57894737 ... 1.         0.         0.        ]
 ...
 [0.75       1.         1.         ... 0.         0.         1.        ]
 [0.05       0.         1.         ... 1.         0.         0.        ]
 [0.         1.         1.         ... 0.         0.         1.        ]]
[[0.34899161]
 [0.63418097]
 [0.05887511]
 ...
 [0.00521942]
 [0.01473966]
 [0.01995908]]
(495061, 22) (495061, 1)
(55007, 22) (55007, 1)
[[0.28903086]
 [0.2525784 ]
 [0.24794355]
 ...
 [0.19366153]
 [0.18476763]
 [0.36272913]]


In [31]:
model = keras.Sequential(
    [
        layers.Dense(128, activation="relu", input_shape=(x_train.shape[-1],)),
        layers.Dense(256, activation="relu"),
        layers.Dense(128, activation="relu"),
        layers.Dense(64, activation="relu"),
        layers.Dense(1, activation="relu"),
    ]
)
model.summary()

model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.05, momentum=0.04, nesterov=False, name="SGD"), 
              loss=keras.losses.MeanSquaredError(),
             metrics=[keras.metrics.SparseCategoricalAccuracy(name="acc")])

model.fit(x_train,y_train,batch_size=41255,epochs=100)

print('val')
model.fit(x_test,y_test,batch_size=440,epochs=1)

model.layers[2].output.get_shape()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 128)               2944      
_________________________________________________________________
dense_6 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_7 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_8 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 65        
Total params: 77,185
Trainable params: 77,185
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
13/13 [==============================] - 0s 9ms/step - loss: 0.0714 - acc: 1.9190e-04
Epoch 2/100
13/13 

13/13 [==============================] - 0s 8ms/step - loss: 0.0380 - acc: 1.9190e-04
Epoch 74/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0383 - acc: 1.9190e-04
Epoch 75/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0383 - acc: 1.9190e-04
Epoch 76/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0381 - acc: 1.9190e-04
Epoch 77/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0380 - acc: 1.9190e-04
Epoch 78/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0377 - acc: 1.9190e-04
Epoch 79/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0377 - acc: 1.9190e-04
Epoch 80/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0378 - acc: 1.9190e-04
Epoch 81/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0383 - acc: 1.9190e-04
Epoch 82/100
13/13 [==============================] - 0s 8ms/step - loss: 0.0382 - acc: 1.9190e-04
Epoch 83/100
13/13 [===

TensorShape([None, 128])

In [34]:
get_3rd_layer_output = K.function([model.layers[0].input],
                                  [model.layers[4].output])
layer_output = get_3rd_layer_output([x_val_scaled])[0]

# ok = layer_output
ok = scaler.inverse_transform(layer_output)
print(layer_output.shape)
# scaler.inverse_transform(layer_output)

with open("result.csv", 'w', newline='') as f:
    csv.writer(f).writerows(ok)

(233599, 1)
